---
version: "2.20"

services:
  miniflux_db:
    image: postgres:13
    restart: always
    volumes:
      - "/data/miniflux/postgres:/var/lib/postgresql/data"
    env_file:
      - "/etc/infrastructure/miniflux.env"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 3s
      start_period: 5s

  miniflux:
    image: miniflux/miniflux:latest
    restart: always
    depends_on:
      miniflux_db:
        condition: service_healthy
    ports:
      - "8998:8080"
    env_file:
      - "/etc/infrastructure/miniflux.env"
    environment:
      - "RUN_MIGRATIONS=1"
      - "CREATE_ADMIN=1"
