op-inject:
    op inject -i ./terraform.tfvars.templ -o ./terraform.tfvars --force

op-load-state:
    op document get --vault infrastructure terraform.tfstate -o ./terraform.tfstate --force

op-save-state:
    op document edit --vault infrastructure terraform.tfstate ./terraform.tfstate

op-init-state:
    op document create --vault infrastructure ./terraform.tfstate

init: op-inject op-load-state
    terraform init -var-file=terraform.tfvars

plan: op-inject op-load-state
    terraform plan -var-file=terraform.tfvars

apply: op-inject op-load-state && op-save-state
    terraform apply -auto-approve -var-file=terraform.tfvars
